// This file is auto-generated by Lingui
// Import this file to load the messages for the English locale

export const en = {
  messages: {
    "headline": "Music",
    "lastListened": "Last listened",
    "visitUserProfile": "Visit user profile",
    "time.seconds": "seconds",
    "time.minutes": "minutes",
    "time.hours": "hours",
    "time.days": "days",
    "github": "Show code of this project on GitHub"
  }
};