name: Dependencies Cron

on:
  workflow_dispatch:

jobs:
  deploy:
    environment: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hasundue/molt-action@v1
