name: Deploy

on:
  push:
    branches:
      - dev
    paths:
      - ".github/workflows/deploy.yml"
      - "supabase/**"
      - "!**.md"
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 'Supabase - Remote Connect'
        env:
          PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        shell: bash
        run: |
          supabase link --project-ref $PROJECT_ID
          supabase db push
          supabase functions deploy
