name: Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # migrations
      - run: supabase db push --project-ref $PROJECT_ID

      # functions
      - run: supabase functions deploy --project-ref $PROJECT_ID