name: Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - ".github/workflows/test.yml"
      - "supabase/**"
      - "!**.md"
  workflow_dispatch:

jobs:
  qa:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno fmt --check supabase/*
      - run: deno lint supabase/*
      - run: deno run tests
