name: Check Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - ".github/workflows/test-web.yml"
      - "src/web/**"
      - "!**.md"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  qa:
    name: 'QA'
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # Supabase
      - name: 'Check Outdated Supabase packages'
        uses: ./.github/workflows/deno-outdated/action.yml
        id: outdated_supabase
        with:
          working-directory: ./

      # Web
      - name: 'Check Outdated Web packages'
        uses: ./.github/workflows/deno-outdated/action.yml
        id: outdated
        with:
          working-directory: src/web

      - name: 'Build Web'
        run: |
          cd src/web
          deno task build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/web/dist

      - name: 'Outdated packages - post'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          header: outdated
          message: |
            ## Outdated Dependencies:
            
            ### Supabase
            ${{ steps.outdated_supabase.outputs.result }}

            ### Web
            ${{ steps.outdated_web.outputs.result }}