name: Check Supabase

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - ".github/workflows/test-supabase.yml"
      - "supabase/**"
      - "!**.md"
  workflow_dispatch:

env:
  PROJECT_ID: xxx
  PROJECT_PUBLISHABLE_KEY: yyy

jobs:
  qa:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno fmt --check supabase/*
      - run: deno lint supabase/*
      - run: deno run tests

      - name: 'Generate cron jobs'
        uses: actions/upload-artifact@v4
        with:
          name: cron_jobs.sql
          path: cron_jobs.sql
          retention-days: 1