name: Check Web

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - ".github/workflows/test-web.yml"
      - "src/web/**"
      - "!**.md"
  workflow_dispatch:

jobs:
  qa:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build
        run: |
          cd src/web
          deno task build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/web/dist
